name: softx_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_test: 
    sdk: flutter
flutter_localizations:
  sdk: flutter
  version: ^0.0.0

flutter: 
  uses-material-design: true

