name: softx_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  carousel_slider: ^4.0.0
#  flutter_inappwebview: ^5.3.2
  marquee: ^2.2.1
  flutter_share: ^2.0.0
  shimmer: ^2.0.0
  dio: ^4.0.4
  url_launcher: ^6.0.20

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_test: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/



